### ISSUE TITLE
Text field focus & MVP

### ISSUE THREAD

**Issue by cometman** [Neuro-ID/neuroid-android-sdk#11]
- [x] On a textfield focus, a focus event is sent
- [x] On a text change, there is a INPUT & keydown event with valid payloads. Use the google sheet, and timcapsule website for examples
- [x] on a textfield blur, a blur event is sent
- [x] on a textfield blur, a textchange event is fired with a valid payload.. Previously I had directed this should be on every character change, which is incorrect. This should only fire after a field deselected/blured
- [x] Ensure all events have unit tests
- [x] Ensure event is being sent to neuro-id API and you are receiving a succesful response
- [x] Update readme with any install/build instructions
- [x] Push all code to github
- [ ] Schedule code review with Clay & Alexis

**Comment by DiegoMGonet** [comment]
Hi @cometman , I have a questions:
1. In the payload of event KEYDOWN, What does "kc" mean? What value should I send?
2. When I detect KEYDOWN event I send also INPUT event, is it right?
3. OK
4. On BLUR event, I should send a TEXT_CHANGE of the field that was blurred, is that correct?

**Comment by cometman** [comment]
Hey Diego, first of all thank you for being so flexible. The requirements are rapidly changing as we iterate on the iOS SDK with our data science team.

1) For now, SKIP the keydown event completely. 
2) Only send input
4) Correct

**Comment by DiegoMGonet** [comment]
Hi Clay, I have finished adding the changes to the edittext events, I am attaching here an example of how the request is being sent from an Android, so you can see how I send the form parameters, and let me know if you want me to change something. I also add the json that contains the events of the EditText.

**First request to the server and the response:**
<img width="1246" alt="Captura de Pantalla 2022-02-03 a la(s) 6 33 08 p m" src="https://user-images.githubusercontent.com/95249706/152452494-96aea79f-d7e0-4609-a61a-47917cd00935.png">

**The json with the events captured from the edittext**
<img width="1239" alt="Captura de Pantalla 2022-02-03 a la(s) 6 33 28 p m" src="https://user-images.githubusercontent.com/95249706/152452519-5c8672fd-5822-4031-a0d9-a53f850d6059.png">

**Comment by cometman** [comment]
Looks awesome! Can you setup a time Monday for us to meet and walk through everything?

**Comment by DiegoMGonet** [comment]
Sounds good, except that Monday is a non-working day in Mexico, but if it's urgent, you can define a schedule that day without any problem. Greetings

**Comment by cometman** [comment]
Diego, I would never have you come in on holiday!!! Drink an extra cervesa for me! Talk to you Tuesday.

**Comment by DiegoMGonet** [comment]
It's not a problem man, thank you very much, I will do it. See you on Tuesday!
