### ISSUE TITLE
Setup Android Google Play account & upload build

### ISSUE THREAD

**Issue by cometman** [Neuro-ID/neuroid-android-sdk#16]
- [x] Setup Google Play Team account
- [x] Add clay.selby@neuro-id.com as admin
- [x] Create an internal testing team (add both of us as testers)
- [x] Upload build of test application to the internal test
- [x] Download the test build to your android phone and validate distribution of test versions is working

**Comment by DiegoMGonet** [comment]
Hello Clay, I already created the google play account, and the app demo is ready to upload. But I need to upload in release mode. I have two doubts:
1. In release mode, do you want to keep leaving the Test environment url? (https://api.usw2-dev1.nidops.net/v3/c)
2. In release mode, the logs are not shown, how could we test if it works correctly? That is, you could only interact with the application.

**Comment by cometman** [comment]
- Use the production url
-Dont show logs in release mode
