### ISSUE TITLE
Update sandbox application

### ISSUE THREAD

**Issue by cometman** [Neuro-ID/neuroid-android-sdk#17]
- [x] Create separate respository for example android application
- [ ] Remove example application from the SDK respository
- [x] Update the example applicaiton with the new users interface linked below

**Comment by cometman** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/1221486/157104146-3c989ebd-54ba-4088-8aa2-49d3eccb9960.png">

**Comment by cometman** [comment]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/1221486/157104260-9a28c3bc-14f2-4834-8047-111008a06c70.png">

**Comment by DiegoMGonet** [comment]
Perfect, @cometman , Is it just 2 screens?

**Comment by cometman** [comment]
One screen, just scrolls down

**Comment by DiegoMGonet** [comment]
@cometman Would you like the button to do something in particular when I pressed it? * The button "Agree and Check Your Loan Options"

**Comment by DiegoMGonet** [comment]
@cometman Can you share me the "NEURO-ID®" icon please?
