### ISSUE TITLE
Full coverage of all Track Events

### ISSUE THREAD

**Issue by cometman** [Neuro-ID/neuroid-android-sdk#4]
Link to all events: Events in RED do not implement. Update this list with progress. https://docs.google.com/spreadsheets/d/1wGgyXCHkFrQ4hPQEhDSq1J7KFhEgNdU40aV3btTo6ZA/edit?usp=sharing

- [x] Establish SDK requirements (min android version)
- [x] Register all valid targets
- [x] All user input events
- [x] All application/window events

**Comment by cometman** [comment]
- [ ] Automatically register all valid input targets within and Android view with collector endpoint.
- [ ] Automatically track all views/fragments loading/unloading

**Comment by cometman** [comment]
This will be your first ticket @DiegoMGonet

**Comment by cometman** [comment]
Make sure to set the `form_data` fields for all requests to the API. The `url` field will be the name of the View/Fragment the event is associated with. 

<img width="921" alt="Screen Shot 2022-01-24 at 12 20 24 PM" src="https://user-images.githubusercontent.com/1221486/150849741-02d40c62-1ed1-4325-8ee3-6ff969e6c0b8.png">

**Comment by DiegoMGonet** [comment]
**1. Establish SDK requirements (min android version):**  The recommended minimum is api version 21, also known as version 5.0 or Lollipop, because it is the one that marks by default when starting any project in Android Studio and because it covers 98% of all devices worldwide.

<img width="779" alt="Captura de Pantalla 2022-01-24 a la(s) 1 30 14 p m" src="https://user-images.githubusercontent.com/95249706/150852166-cfb2728b-6bd3-40fe-b8c9-6951f902850b.png">

**Comment by DiegoMGonet** [comment]
**2. Register all valid targets:** The views that are considered that the user can interact with them are registered, which are:

1. EditText (Text field)
2. CheckBox
3. RadioButton
4. ToggleButton (allow the users to change the setting between two states like turn on/off)
5. Switch
6. Button
7. Seekbar (Slider)
8. Spinner (Combo box)

**Comment by DiegoMGonet** [comment]
**3. All user input events:** The events captured by the interaction of the inputs are found in the document: [https://docs.google.com/spreadsheets/d/1wGgyXCHkFrQ4hPQEhDSq1J7KFhEgNdU40aV3btTo6ZA/edit?usp=sharing](url), Of which it is indicated which ones cannot be registered and why:
1. Key Up: Called when a hardware key is dispatched to a view. This allows listeners to get a chance to respond before the target view. Key presses in software keyboards will generally NOT trigger this method. Do not assume a software input method has to be key-based, so there is no way to reliably catch soft input key presses. link: [https://developer.android.com/reference/android/view/View.OnKeyListener](url)
2. Touch cancel: In Android there is no indicator of a touch cancel, it could also be interpreted when the user lifts his finger from the screen (Touch end)

**Comment by DiegoMGonet** [comment]
**4. All application/window events:** The windows events, in android called lifecycle, are already implemented:
1. Activities: 
- onStart: WINDOW_LOAD
- onResume: WINDOW_FOCUS
- onPause: WINDOW_BLUR
- onDestroy: WINDOW_UNLOAD

2. Fragments (windows inside the activity):
- onAttach: WINDOW_LOAD
- onViewCreate: WINDOW_FOCUS
- onPause: WINDOW_BLUR
- onDetach: WINDOW_UNLOAD

Application events that cannot be captured are:
1. Touch cancel: In Android there is no indicator of a touch cancel, it could also be interpreted when the user lifts his finger from the screen (Touch end)

**Comment by DiegoMGonet** [comment]
@cometman , You mentioned that the url is associated with the event, but there are several events that may have been previously saved in another activity or fragment, would you put the last activity or fragment that was displayed in the url field?

**Comment by cometman** [comment]
@DiegoMGonet I would say, whatever the activity or fragment they were associated with last, lets use that. If there is no fragment reference available, just use the current activity/fragment.
