### ISSUE TITLE
Unit test coverage of all Track events

### ISSUE THREAD

**Issue by cometman** [Neuro-ID/neuroid-android-sdk#5]
- [x] All Track events covered with a unit test

**Comment by cometman** [comment]
List any events you cannot test in the comments here.

**Comment by DiegoMGonet** [comment]
Currently for the generation of the ui tests we are using Android libraries, called "Espresso" [https://developer.android.com/training/testing/espresso](url), it helps us to interact with the activities, fragments and inputs, but it does not have the scope of making tests interacting with the device. The events that could not be generated by ui tests are:

1.  Device orientation: Unable to manipulate the device with "Espresso"
2. Window orientation change: Possible duplication with Device orientation?
3. Device motion: Unable to manipulate the device with "Espresso"
4. Copy, Cut, Paste events: They are events that are made up of several gestures (Text selection, long click on the text, not on the field, selection of an editing option), which cannot be recreated in the "Espresso" documentation
